### ISSUE TITLE
Constantly Not Solved

### ISSUE THREAD

**Issue by klocke** [a-maliarov/amazoncaptcha#32]
![unsolveable-captcha](https://user-images.githubusercontent.com/17553693/102722542-fd61b780-4301-11eb-9222-f7532a638b6f.jpg)

**Paste the code showing which endpoint of the AmazonCaptcha library you are using**
```python
    captcha_link = "https://user-images.githubusercontent.com/17553693/102722542-fd61b780-4301-11eb-9222-f7532a638b6f.jpg"
    captcha = AmazonCaptcha.fromlink(captcha_link)
    solution = captcha.solve()
    print("Captcha solution is: ", solution)
```

**Is it really constant?**
How many captchas in a row have given the "Not Solved" result?
All!

**Environment (please complete the following information):**
 - OS: macOS 10.15
 - Driver chrome
 - Driver version ChromeDriver 87.0.4280.88

**Additional context**
Hi, I am trying to solve this type of Captcha seen in the attached photo that occurs while logging into an Amazon account. I have tried loading it in different ways and the img is loaded correctly, anyway I always get a "Not Solved." response.

**Comment by a-maliarov** [comment]
Hi! Thanks for the detailed report but, unfortunately, this type of Amazon captcha (yeah, it has like 3 of them) is not supported and was not considered to be added. Currently, you will not be be able to solve this captcha using `amazoncaptcha` library.

There are two things you can do for now:
+ share the way how, for example, I can constantly find this captcha on Amazon website. To create a solver, there should be approximately a ton of samples. I do not guarantee that it will be 100% possible to create a solver with a ton of samples, but it will be impossible without them.
+ if you are trying to login into only one account, try googling "selenium cookies login".
