### ISSUE TITLE
Won't launch properly 

### ISSUE THREAD

**Issue by loudram** [a-maliarov/amazoncaptcha#43]
The project won't work or boot with the code imported. I'm using pycharm with a virtual environment on a Windows machine. I get the error "can't find '__main__' module in {path to project}" anytime I try to run anything, including the example code segments with selenium.

**Comment by loudram** [comment]
Switched over to visual studio code and I don't have the issue.

**Comment by a-maliarov** [comment]
Hi, sorry for the late response, I wasn't able to answer during last months due to some reasons.

Great you were able to solve the issue, have a great day!
