### ISSUE TITLE
How to post the result of Captcha solved

### ISSUE THREAD

**Issue by Anthon02** [a-maliarov/amazoncaptcha#44]
I am looking for code that will post the captcha solution once solved. I don't see mention of how to properly submit it.

Thanks

**Comment by a-maliarov** [comment]
Hi, I was actually thinking about the submission included into the package, but then realized that it's something that will cause more cons than pros.

Therefore, at this point the repository is dedicated to just translate an image into text.

**Comment by barrycarey** [comment]
@a-maliarov Do you have an example of how to post at-least?  I've been trying and failing to submit a solved captcha via Requests.
