### ISSUE TITLE
Make Selenium dependency optional

### ISSUE THREAD

**Issue by dvukolovAC** [a-maliarov/amazoncaptcha#56]
Would it be possible to make Selenium dependency optional? Currently, the dependency tree for a project that imports `amazoncaptcha` shows that the majority of packages are coming from Selenium:

```{shell}
$ pipdeptree -p amazoncaptcha
amazoncaptcha==0.5.5
  - pillow [required: ~=9.0.1, installed: 9.0.1]
  - requests [required: ~=2.27.1, installed: 2.27.1]
    - certifi [required: >=2017.4.17, installed: 2021.10.8]
    - charset-normalizer [required: ~=2.0.0, installed: 2.0.11]
    - idna [required: >=2.5,<4, installed: 3.3]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.8]
  - selenium [required: >=3.141,<4.2, installed: 4.1.0]
    - trio [required: ~=0.17, installed: 0.19.0]
      - async-generator [required: >=1.9, installed: 1.10]
      - attrs [required: >=19.2.0, installed: 21.4.0]
      - cffi [required: >=1.14, installed: 1.15.0]
        - pycparser [required: Any, installed: 2.21]
      - idna [required: Any, installed: 3.3]
      - outcome [required: Any, installed: 1.1.0]
        - attrs [required: >=19.2.0, installed: 21.4.0]
      - sniffio [required: Any, installed: 1.2.0]
      - sortedcontainers [required: Any, installed: 2.4.0]
    - trio-websocket [required: ~=0.9, installed: 0.9.2]
      - async-generator [required: >=1.10, installed: 1.10]
      - trio [required: >=0.11, installed: 0.19.0]
        - async-generator [required: >=1.9, installed: 1.10]
        - attrs [required: >=19.2.0, installed: 21.4.0]
        - cffi [required: >=1.14, installed: 1.15.0]
          - pycparser [required: Any, installed: 2.21]
        - idna [required: Any, installed: 3.3]
        - outcome [required: Any, installed: 1.1.0]
          - attrs [required: >=19.2.0, installed: 21.4.0]
        - sniffio [required: Any, installed: 1.2.0]
        - sortedcontainers [required: Any, installed: 2.4.0]
      - wsproto [required: >=0.14, installed: 1.0.0]
        - h11 [required: >=0.9.0,<1, installed: 0.13.0]
    - urllib3 [required: ~=1.26, installed: 1.26.8]
```

Given that `AmazonCaptcha` is fully functional without Selenium, as well as a wealth of alternatives to Selenium exist when an automated browser is required (Playwright, pyppeteer), there seems to be an opportunity to make the package lighter. If I understand it correctly, at the moment Selenium is only imported for unit tests. In production the expectation is for the user to install & import Selenium, then pass the driver object to `AmazonCaptcha`. Therefore two separate production and test requirements (with an optional version compatibility check in production) should do the trick. Thanks!

**Comment by a-maliarov** [comment]
Hi, it was actually a question in my head on whether selenium should be a requirement. It was not initially, but I decided to add it anyways because of `fromdriver` class method. Although, the request is completely understandable and I think I will remove Selenium from dependancies list within the next version.

**Comment by a-maliarov** [comment]
After some consideration, I think it's safe to remove selenium from required dependencies, since if someone uses `fromdriver`, they are supposed to already have selenium installed.
