### ISSUE TITLE
Does it work on Amazon's new captcha system

### ISSUE THREAD

**Issue by yankedong** [a-maliarov/amazoncaptcha#61]
It seems that Amazon has upgraded its captcha system. 
![WechatIMG657](https://user-images.githubusercontent.com/78668967/162354853-e58cc5fb-4dca-4ace-a742-aa1579b8c257.png)

Does the code still work?

**Comment by a-maliarov** [comment]
Library supports only [this](https://www.amazon.com/errors/validateCaptcha) type of captcha. The one that you posted is more of an exception and it won't be included into the library.

**Comment by yankedong** [comment]
> Library supports only [this](https://www.amazon.com/errors/validateCaptcha) type of captcha. The one that you posted is more of an exception and it won't be included into the library.

Thanks for your quick reply.

**Comment by merry75** [comment]
> Library supports only [this](https://www.amazon.com/errors/validateCaptcha) type of captcha. The one that you posted is more of an exception and it won't be included into the library.

what do you men an exception ? :d happened to me quite frequently , you know a lib or a service that deals with this one ?
man the employees at amazon are so bored these days that they try to break our automation scripts or what ?

**Comment by a-maliarov** [comment]
@merry75 where do you meet this type (I mean the one mentioned by OP)? on what pages?

**Comment by wengooooo** [comment]
@a-maliarov When you register an account at amazon.cn you will see this verification code

**Comment by a-maliarov** [comment]
> @a-maliarov When you register an account at amazon.cn you will see this verification code

I see, yep, this type of captcha won't be supported.

**Comment by merry75** [comment]
when you also login in sometimes

**Comment by a-maliarov** [comment]
@wengooooo @merry75 could you send me the link to this type of captcha? Not a single image, but to the page where it's promted. Thanks.
