### ISSUE TITLE
Can bypass aws puzzle captcha ?

### ISSUE THREAD

**Issue by NonameASecret** [a-maliarov/amazoncaptcha#62]
Below picture it's given captcha . Captcha send by aws waf . Any way to bypass it or sove it?

![IMG_20220517_134747](https://user-images.githubusercontent.com/77895732/168764237-67ce0b53-2092-444a-92d4-5c42a32ebd4b.jpg)

**Comment by NonameASecret** [comment]
**Captcha Example Below**


![IMG_20220517_134747](https://user-images.githubusercontent.com/7511692/141794044-1b56d67a-d086-4bdf-865a-fefd34f2c9ce.gif)

**Comment by a-maliarov** [comment]
> ... solver for [Amazon's text captcha](https://www.amazon.com/errors/validateCaptcha).

The library supports only the mentioned type of captcha.

**Comment by NonameASecret** [comment]
> > ... solver for [Amazon's text captcha](https://www.amazon.com/errors/validateCaptcha).
> 
> The library supports only the mentioned type of captcha.

tha nk you. are you know method for this [captcha](https://github.com/a-maliarov/amazoncaptcha/issues/62#issuecomment-1128567899)
