### ISSUE TITLE
Performance enhancement 

### ISSUE THREAD

**Issue by mrahmadt** [a-maliarov/amazoncaptcha#75]
Hello

how can I enhance the performance of amazoncaptcha?

i have hundred of thousands of images and the CPU consumption is high

any recommendations or suggestion for other tools?

Thanks

**Comment by a-maliarov** [comment]
Doesn't it have to be high if you are processing hundreds of thousands of images? I mean... :D

**Comment by mrahmadt** [comment]
Thanks

I didn’t get your point

but when I run parallel 200 process I get around 5%-7% cpu consumed  per amazoncaptcha instance

**Comment by a-maliarov** [comment]
If you running 200 processess at the same time, your high CPU consumption is probably caused by the fact that: you. are. running. 200. processes. simultaneously XD
