### ISSUE TITLE
Constantly Not Solved

### ISSUE THREAD

**Issue by iceman-twitch** [a-maliarov/amazoncaptcha#91]
The current issue is the new version of AmazonCaptcha is different from the validateCaptcha site.
If I try to login I get this kind of image. Image Solver cant solve it.

[Image](https://ibb.co/z4B0ddq)

**Comment by a-maliarov** [comment]
It's not new and's been around for quite some time, this package is not intended to solve this type of captcha, only the https://www.amazon.com/errors/validateCaptcha

**Comment by RileyXX** [comment]
> ![Image](https://i.ibb.co/CHYTLLR/a.jpg)

@kem008 Did you ever find a captcha solver that works with these types of images? 

I'm looking for a captcha solver to my IMDB syncer script which mainly uses these images. Any suggestions @a-maliarov ?
